export const GET_ALL_TICKETS_REQUEST = 'GET_ALL_TICKETS_REQUEST';
export const GET_ALL_TICKETS_SUCCESS = 'GET_ALL_TICKETS_SUCCESS';
export const GET_ALL_TICKETS_FAILURE = 'GET_ALL_TICKETS_FAILURE';

export const POST_BOOK_TICKETS_REQUEST = 'POST_BOOK_TICKETS_REQUEST';
export const POST_BOOK_TICKETS_SUCCESS = 'POST_BOOK_TICKETS_SUCCESS';
export const POST_BOOK_TICKETS_FAILURE = 'POST_BOOK_TICKETS_FAILURE';

export const PATCH_CANCEL_TICKET_REQUEST = 'PATCH_CANCEL_TICKET_REQUEST';
export const PATCH_CANCEL_TICKET_SUCCESS = 'PATCH_CANCEL_TICKET_SUCCESS';
export const PATCH_CANCEL_TICKET_FAILURE = 'PATCH_CANCEL_TICKET_FAILURE';